### ISSUE TITLE
Third parameter is missing

### ISSUE THREAD

**Issue by Kaperstone** [ZOTTCE/samp-plugin-example#1]
This will error due to no third parameter in place.
https://github.com/ZOTTCE/samp-plugin-example/blob/2d96513b0303a1c7111494410e584c3610dc16b5/src/plugin.rs#L81

Moreover, size doesn't seem to be used?
https://github.com/ZOTTCE/samp-plugin-example/blob/2d96513b0303a1c7111494410e584c3610dc16b5/src/plugin.rs#L76
This will warn of "unused parameter".

**Comment by zottce** [comment]
Oh, sorry!
Forgot to edit the example.
[Here](https://docs.rs/samp-sdk/0.8.1/samp_sdk/macro.set_string.html) is a new `set_string!` signature. There is third (size) argument now.
